// Generated by Wrangler on Thu May 30 2024 14:27:40 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	hubspotOAuthStore: KVNamespace;
	CLIENT_ID: string;
	CLIENT_SECRET: string;
	PLUGIN_URI: string;
	REDIRECT_URI: string;
	AUTHORIZE_ENDPOINT: string;
	TOKEN_ENDPOINT: string;
	SCOPE: string;
}
